version: "3"

services:
  file-server:
    build:
      context: .
      dockerfile: ./file-server.dockerfile
    ports:
      - "8080:8080"
    networks:
      - my_network
    volumes:
      - ./uploads:/app/uploads

networks:
  my_network:
    external: true
